import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateEventTable1750470044519 implements MigrationInterface {
    name = 'CreateEventTable1750470044519'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`teams\` DROP FOREIGN KEY \`teams_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`invitations\` DROP FOREIGN KEY \`fk_invitations_invitee\``);
        await queryRunner.query(`ALTER TABLE \`invitations\` DROP FOREIGN KEY \`fk_invitations_team\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`projects_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`projects_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_assigned_user\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`tasks_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`tasks_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`team_members_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`team_members_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`FK_e300b5c2e3fefa9d6f8a3f25975\` ON \`documents\``);
        await queryRunner.query(`DROP INDEX \`FK_a7435dbb7583938d5e7d1376041\` ON \`files\``);
        await queryRunner.query(`DROP INDEX \`idx_folders_user_parent\` ON \`folders\``);
        await queryRunner.query(`DROP INDEX \`creator_id\` ON \`teams\``);
        await queryRunner.query(`DROP INDEX \`idx_invitations_teamId\` ON \`invitations\``);
        await queryRunner.query(`DROP INDEX \`teamId\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`userId\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`projectLeadId\` ON \`projects\``);
        await queryRunner.query(`DROP INDEX \`teamId\` ON \`projects\``);
        await queryRunner.query(`DROP INDEX \`assignedToId\` ON \`tasks\``);
        await queryRunner.query(`DROP INDEX \`projectId\` ON \`tasks\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`team_members\``);
        await queryRunner.query(`CREATE TABLE \`events\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`start\` datetime NOT NULL, \`end\` datetime NOT NULL, \`allDay\` tinyint NOT NULL DEFAULT 0, \`userId\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profile_picture\``);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP COLUMN \`projectLeadId\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`assignedToId\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD \`shared_with\` text NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`user_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`folder_id\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`folder_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`shared_with\` text NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`user_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`parent_id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`parent_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`creator_id\``);
        await queryRunner.query(`ALTER TABLE \`teams\` ADD \`creator_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` CHANGE \`createdAt\` \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`invitations\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`createdAt\` \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`teamId\` \`teamId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`assignedUserId\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`assignedUserId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`status\` enum ('To Do', 'In Progress', 'Done') NOT NULL DEFAULT 'To Do'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD PRIMARY KEY (\`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD \`user_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD PRIMARY KEY (\`team_id\`, \`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fdad7d5768277e60c40e01cdce\` ON \`team_members\` (\`team_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_c2bf4967c8c2a6b845dadfbf3d\` ON \`team_members\` (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD CONSTRAINT \`FK_e300b5c2e3fefa9d6f8a3f25975\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_a7435dbb7583938d5e7d1376041\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_27bc84e6954d2fa309a4f61326f\` FOREIGN KEY (\`folder_id\`) REFERENCES \`folders\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD CONSTRAINT \`FK_71af7633de585b66b4db26734c9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD CONSTRAINT \`FK_938a930768697b6ece215667d8e\` FOREIGN KEY (\`parent_id\`) REFERENCES \`folders\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teams\` ADD CONSTRAINT \`FK_42744d21c558ffeb2b57a1f6a1a\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`FK_2f789e58a882d8dd5b936c747c2\` FOREIGN KEY (\`teamId\`) REFERENCES \`teams\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_e08fca67ca8966e6b9914bf2956\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_cf34ff7f1de7b973b7ad5f536de\` FOREIGN KEY (\`assignedUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`events\` ADD CONSTRAINT \`FK_9929fa8516afa13f87b41abb263\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_fdad7d5768277e60c40e01cdcea\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_c2bf4967c8c2a6b845dadfbf3d4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_c2bf4967c8c2a6b845dadfbf3d4\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_fdad7d5768277e60c40e01cdcea\``);
        await queryRunner.query(`ALTER TABLE \`events\` DROP FOREIGN KEY \`FK_9929fa8516afa13f87b41abb263\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_cf34ff7f1de7b973b7ad5f536de\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP FOREIGN KEY \`FK_e08fca67ca8966e6b9914bf2956\``);
        await queryRunner.query(`ALTER TABLE \`projects\` DROP FOREIGN KEY \`FK_2f789e58a882d8dd5b936c747c2\``);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP FOREIGN KEY \`FK_42744d21c558ffeb2b57a1f6a1a\``);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP FOREIGN KEY \`FK_938a930768697b6ece215667d8e\``);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP FOREIGN KEY \`FK_71af7633de585b66b4db26734c9\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_27bc84e6954d2fa309a4f61326f\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_a7435dbb7583938d5e7d1376041\``);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP FOREIGN KEY \`FK_e300b5c2e3fefa9d6f8a3f25975\``);
        await queryRunner.query(`DROP INDEX \`IDX_c2bf4967c8c2a6b845dadfbf3d\` ON \`team_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_fdad7d5768277e60c40e01cdce\` ON \`team_members\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD PRIMARY KEY (\`team_id\`)`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD PRIMARY KEY (\`team_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`status\` varchar(50) NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`tasks\` DROP COLUMN \`assignedUserId\``);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`assignedUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`teamId\` \`teamId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`updatedAt\` \`updatedAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`projects\` CHANGE \`createdAt\` \`createdAt\` timestamp(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`invitations\` CHANGE \`createdAt\` \`createdAt\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`teams\` CHANGE \`createdAt\` \`createdAt\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`creator_id\``);
        await queryRunner.query(`ALTER TABLE \`teams\` ADD \`creator_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`parent_id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`parent_id\` char(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`user_id\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folders\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD \`id\` char(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`folders\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`shared_with\` json NULL DEFAULT '_utf8mb4\'[]\''`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`folder_id\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`folder_id\` char(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`files\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP COLUMN \`shared_with\``);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD \`shared_with\` json NULL DEFAULT '_utf8mb4\'[]\''`);
        await queryRunner.query(`ALTER TABLE \`documents\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`documents\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD \`assignedToId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD \`projectLeadId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` ADD \`created_at\` timestamp NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profile_picture\` varchar(512) NULL`);
        await queryRunner.query(`DROP TABLE \`events\``);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`team_members\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`projectId\` ON \`tasks\` (\`projectId\`)`);
        await queryRunner.query(`CREATE INDEX \`assignedToId\` ON \`tasks\` (\`assignedToId\`)`);
        await queryRunner.query(`CREATE INDEX \`teamId\` ON \`projects\` (\`teamId\`)`);
        await queryRunner.query(`CREATE INDEX \`projectLeadId\` ON \`projects\` (\`projectLeadId\`)`);
        await queryRunner.query(`CREATE INDEX \`userId\` ON \`messages\` (\`userId\`)`);
        await queryRunner.query(`CREATE INDEX \`teamId\` ON \`messages\` (\`teamId\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_invitations_teamId\` ON \`invitations\` (\`teamId\`)`);
        await queryRunner.query(`CREATE INDEX \`creator_id\` ON \`teams\` (\`creator_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_folders_user_parent\` ON \`folders\` (\`user_id\`, \`parent_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_a7435dbb7583938d5e7d1376041\` ON \`files\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_e300b5c2e3fefa9d6f8a3f25975\` ON \`documents\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\` (\`username\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`team_members_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`team_members_ibfk_1\` FOREIGN KEY (\`team_id\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`tasks_ibfk_2\` FOREIGN KEY (\`assignedToId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`tasks_ibfk_1\` FOREIGN KEY (\`projectId\`) REFERENCES \`projects\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tasks\` ADD CONSTRAINT \`FK_assigned_user\` FOREIGN KEY (\`assignedUserId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`projects_ibfk_2\` FOREIGN KEY (\`projectLeadId\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`projects\` ADD CONSTRAINT \`projects_ibfk_1\` FOREIGN KEY (\`teamId\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_2\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_1\` FOREIGN KEY (\`teamId\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invitations\` ADD CONSTRAINT \`fk_invitations_team\` FOREIGN KEY (\`teamId\`) REFERENCES \`teams\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invitations\` ADD CONSTRAINT \`fk_invitations_invitee\` FOREIGN KEY (\`inviteeId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`teams\` ADD CONSTRAINT \`teams_ibfk_1\` FOREIGN KEY (\`creator_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
